version: "3"
services:
    db:
        image: groonga/pgroonga:latest
        environment:
            - "POSTGRES_HOST_AUTH_METHOD=trust"
            - "LANG=ja_JP.utf8"
        volumes:
            - ./pgsql-data:/var/lib/postgresql/data
    web:
        build:
            context: .
            dockerfile: Dockerfile_nginx
        volumes:
            - ./public:/usr/share/nginx/public:cached
        ports:
            - 80:80
        depends_on:
            - app
    app:
        build: .
        command: bundle exec rails server -b 0.0.0.0
        volumes:
            - ./:/myapp:cached
        depends_on:
            - db
        environment:
            RAILS_ENV: production
            NODE_ENV: production
            SECRET_KEY_BASE: StudyBook
            MYAPP_DATABASE_PASSWORD: StudyBook
    influxdb:
        image: influxdb:1.8
        environment:
            - INFLUXDB_DB=study_book_db
            - INFLUXDB_USER=study
            - INFLUXDB_USER_PASSWORD=studybook
            - INFLUXDB_ADMIN_USER=root
            - INFLUXDB_ADMIN_PASSWORD=admin
            - INFLUXDB_HTTP_FLUX_ENABLED=true
            - INFLUXDB_HTTP_AUTH_ENABLED=true
            - INFLUXDB_RESPONTING_DISABLED=true
            - INFLUXDB_DATA_MAX_SERIES_PER_DATABASE=0
            - INFLUXDB_DATA_MAX_VALUES_PER_TAG=0
        ports:
            - 8086:8086
        volumes:
            - ./influx_init.iql:/docker-entrypoint-initdb.d/influx_init.iql/
            - ./influx:/var/lib/influxdb
